#! /bin/sh

# Autostarts
pgrep -x lxqt-policykit-agent > /dev/nulll || lxqt-policykit-agent &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar bspwm &
pgrep -x picom > /dev/null || picom &
pgrep -x nitrogen > /dev/null || nitrogen --restore &
pgrep -x dunst > /dev/null || dunst &
sh -c ~/.config/autostart.sh

# Settings
bspc config normal_border_color         "#444444"
bspc config focused_border_color        "#FFFFFF"
bspc config window_gap                  10
bspc config border_width                5
bspc config split_ratio                 0.60
bspc config pointer_follows_monitor     true
bspc config focus_follows_pointer       true
bspc config click_to_focus              true
bspc config presel_feedback_color       "#FFFFFF"

# Monitors
bspc monitor HDMI-0 -d  爵        

# Window Rules
# 10 Games
bspc rule -a Steam desktop='^10' focus=off follow=off
#  9 Chat
bspc rule -a Signal desktop='^9' focus=off follow=off
#  8 VM
bspc rule -a Virt-manager desktop='^8' focus=on follow=on 
#  7 Extra stuff
bspc rule -a KeePassXC desktop='^7' focus=off follow=off
#  6 2D Design
#  5 3D Design
#  4 Files & Notes
bspc rule -a Pcmanfm desktop='^4' focus=on follow=on 
bspc rule -a Cherrytree desktop='^4' focus=on follow=on
bspc rule -a obsidian desktop='^4' focus=on follow=on
#  3 Media
bspc rule -a FreeTube desktop='^3' focus=on follow=on
#  2 Web
bspc rule -a Chromium desktop='^2' focus=on follow=on
bspc rule -a firefox desktop='^2' focus=on follow=on
#  1 Tools
bspc rule -a kitty desktop='^1' focus=on follow=on

# Floating
bspc rule -a kdeconnect.app state=floating center=true
bspc rule -a kcalc state=floating center=true
